    
name: $(BuildDefinitionName)-$(Date:yyyyMMdd).$(Rev:.r)

trigger:
- development

resources:
  repositories:
    - repository: templates
      type: git
      name: pfe-devops-sample-pipelines

jobs:
- template: jobs/build-source-pack-solution.yml@templates